### ISSUE TITLE
How can i get this progress bar via gradle?

### ISSUE THREAD

**Issue by esunilkumare** [yuriy-budiyev/circular-progress-bar#1]
How can i get this progress bar via gradle? Do not see a compile lib.

**Comment by yuriy-budiyev** [comment]
Scince Android Studio 3.0 "compile" has been deprecated. Check this https://developer.android.com/studio/build/gradle-plugin-3-0-0-migration.html.
Anyway, you can jest replace "implementation" word by "compile".
