### ISSUE TITLE
Exposing `setProgressAnimated`

### ISSUE THREAD

**Issue by tyalie** [yuriy-budiyev/circular-progress-bar#4]
I need to have the function `setProgressInternal` exposed as I'll otherwise trigger animations that I don't need and make the UI look wrong.

**Comment by yuriy-budiyev** [comment]
You can disable animation by
app:animateProgress="false"
or
setAnimateProgress(false)

**Comment by tyalie** [comment]
But I need it directly after that.

**Comment by yuriy-budiyev** [comment]
setAnimateProgress(false)
setProgress(...)
setAnimateProgress(true)

**Comment by tyalie** [comment]
Okay sorry. I just found out the reason it doesn't work.

The problem is the following: The app triggers the `setProgress` method in the `onStart()` in order to show a loading circle from the beginning. The problem is that the `setProgressAnimated` function isn't triggered in the `setProgress` if the view isn't visible yet / the `mVisible` is set to false. 

So that this code shows a full circle when the app starts or doesn't work:
```kotlin
with(time_progress_bar) {
    isAnimateProgress = false
    progress = 0f
    isAnimateProgress = true

    progressAnimationDuration = time * 1000L

    progress = 50f
}
```

But this code does show a loading circle when the app is shown:
```kotlin
with(time_progress_bar) {
    isAnimateProgress = false
    progress = 0f
    isAnimateProgress = true

    progressAnimationDuration = time * 1000L

    val setAnimate = time_progress_bar::class.java.getDeclaredMethod("setProgressAnimated", Float::class.java)
    setAnimate.isAccessible = true
    setAnimate.invoke(this, 100f)
}
```

**Comment by yuriy-budiyev** [comment]
I think when a view is shown, it should just show progress value, animations shoud start only for changes and when view is visible. For your case you can just invoke setProgress when layout process is done and view is visible.
You can try something like:
view.getViewTreeObserver().addOnGlobalLayoutListener(...)

**Comment by tyalie** [comment]
Okay. I'll do it then this way. Thanks
