### ISSUE TITLE
Allow for different animation interpolator

### ISSUE THREAD

**Issue by tyalie** [yuriy-budiyev/circular-progress-bar#5]
Giving an animation interpolator to the animator would be great.

**Comment by tyalie** [comment]
I'll add an option for that myself and push it to you for review.

But I have a question about that: Is it possible to set something like that through annotations? How would the implementation look like?

**Comment by yuriy-budiyev** [comment]
Implementation with annotations will require codegen or refelection, both of them seems like too huge overhead for a just progress bar. Classic solution looks good.

**Comment by tyalie** [comment]
One small question: When will the update be released as a Gradle repositories?

**Comment by yuriy-budiyev** [comment]
Soon
